name: Validate JSON

on:
  pull_request:
    paths:
      - '**/*.json'

jobs:
  validate-json:
    name: Validate JSON ✅ # THIS name must exist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Validate all JSON files
        run: |
          for f in $(find . -name '*.json'); do
            echo "Checking $f"
            jq empty "$f"
          done
