name: Validate JSON

on:
  pull_request:
    paths:
      - '**/*.json'
      - '*.json'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate JSON files
      run: |
        for file in $(find . -name "*.json"); do
          echo "Validating $file"
          cat "$file" | jq empty
        done
